"""empty message

Revision ID: 9aac748249e1
Revises: bc821fe2d212
Create Date: 2025-06-05 20:17:26.265730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aac748249e1'
down_revision = 'bc821fe2d212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.drop_constraint('media_post_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('media_post_id_fkey', 'media', ['post_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
